[phases.setup]
aptPkgs = ["ffmpeg", "python3-dev"]
cmds = ["python -m pip install --upgrade pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python bot.py"

[deploy]
restartPolicy = "on-failure"
